/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelView.java
 *
 * Created on Feb 26, 2012, 12:39:44 AM
 */
package sample.jtree.example.ui;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author bahrie
 */
public class PanelView extends javax.swing.JPanel {

    /** Creates new form PanelView */
    public PanelView() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPanel = new sample.jtree.example.util.JPPanel();

        javax.swing.GroupLayout jPPanelLayout = new javax.swing.GroupLayout(jPPanel);
        jPPanel.setLayout(jPPanelLayout);
        jPPanelLayout.setHorizontalGroup(
            jPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPPanelLayout.setVerticalGroup(
            jPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sample.jtree.example.util.JPPanel jPPanel;
    // End of variables declaration//GEN-END:variables
    private String path;

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        Icon icon = new ImageIcon(getClass().getResource(path));
        jPPanel.setIcon(icon);
    }

    
}
