/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelGalery.java
 *
 * Created on Feb 26, 2012, 12:39:33 AM
 */
package sample.jtree.example.ui;

import java.awt.GridLayout;
import javax.swing.JPanel;
import sample.jtree.example.entity.Buah;
import sample.jtree.example.entity.Kategori;
import sample.jtree.example.impl.ImplementKategori;
import sample.jtree.example.interf.KategoriInterface;
import sample.jtree.example.util.GaleryListener;

/**
 *
 * @author bahrie
 */
public class PanelGalery extends javax.swing.JPanel {

    /** Creates new form PanelGalery */
    public PanelGalery() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        gridContent = new javax.swing.JPanel();

        gridContent.setLayout(new java.awt.GridLayout(1, 0, 20, 20));
        scrollPane.setViewportView(gridContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gridContent;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    private String kategori;
    private int idKat;
    private GaleryListener listener;

    public String getKategori() {
        return kategori;
    }

    public void setKategori(String kategori) {
        this.kategori = kategori;
        
    }

    public GaleryListener getListener() {
        return listener;
    }

    public void setListener(GaleryListener listener) {
        this.listener = listener;
    }

    public int getIdKat() {
        return idKat;
    }

    public void setIdKat(int idKat) {
        this.idKat = idKat;
    }

    public void isiGalery() {
        KategoriInterface ki = new ImplementKategori();
        PanelGambar pg;
        Kategori k = ki.getByKat(kategori);
        gridContent.removeAll();
        gridContent.setLayout(new GridLayout(0, 3, 20, 20));
        for (Buah b : k.getListBuah()) {
            pg = new PanelGambar();
            pg.setPath(b.getPath());
            pg.setNameTitle(b.getNama());
            pg.setListener(listener);
            gridContent.add(pg);
        }
    }

    
    
    
}
