/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelGalery.java
 *
 * Created on Feb 26, 2012, 12:39:33 AM
 */
package sample.jtree.example.ui;

import java.awt.GridLayout;
import javax.swing.JComponent;
import javax.swing.JPanel;
import sample.jtree.example.entity.PenyediaData;
import sample.jtree.example.entity.TreeModelData;
import sample.jtree.example.util.GaleryListener;

/**
 *
 * @author bahrie
 */
public class PanelGalery extends javax.swing.JPanel {

    /** Creates new form PanelGalery */
    public PanelGalery() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        gridContent = new javax.swing.JPanel();

        javax.swing.GroupLayout gridContentLayout = new javax.swing.GroupLayout(gridContent);
        gridContent.setLayout(gridContentLayout);
        gridContentLayout.setHorizontalGroup(
            gridContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        gridContentLayout.setVerticalGroup(
            gridContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(gridContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gridContent;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    private int idKat;
    private GaleryListener listener;

    public GaleryListener getListener() {
        return listener;
    }

    public void setListener(GaleryListener listener) {
        this.listener = listener;
    }

    public int getIdKat() {
        return idKat;
    }

    public void setIdKat(int idKat) {
        this.idKat = idKat;
    }

    public void isiGalery(String name) {

//        KategoriInterface ki = new ImplementKategori();

//        Kategori k = ki.getByKat(kategori);

        TreeModelData tmd = PenyediaData.cariTreeModelData(PenyediaData.getListTreeModel(), name);
        PanelGambar pg;

        gridContent.removeAll();
        gridContent.setLayout(new GridLayout(0, 4, 0, 0));
        for (TreeModelData data : tmd.getListTreeModel()) {
            pg = new PanelGambar();
            if (data.getPath() != null) {
                pg.setPath(data.getPath());
                pg.setListener(listener);
            } else {
                pg.setPath("/sample/jtree/images/folder.png");
            }
            pg.setNameTitle(data.getLabel());
            
            gridContent.add(wrap(pg));
        }
    }
    
    public static JComponent wrap(JComponent comp)
    {
        JPanel panel = new JPanel();
        panel.add(comp);
        return panel;
    }
}
